# Generated by Django 4.2.1 on 2023-09-29 13:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日付')),
                ('ds', models.CharField(choices=[(1, '日中一時'), (2, '生活介護'), (3, '併給')], max_length=1)),
                ('start_time', models.TimeField(default=datetime.time(10, 0), verbose_name='開始時刻')),
                ('end_time', models.TimeField(default=datetime.time(15, 0), verbose_name='終了時刻')),
                ('bathing', models.BooleanField(default=True, verbose_name='入浴')),
                ('transportation', models.BooleanField(default=True, verbose_name='送迎')),
                ('meal', models.BooleanField(default=True, verbose_name='食事')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
            ],
        ),
        migrations.CreateModel(
            name='AddonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_price', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Class_NUM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Class_OBST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=20, verbose_name='利用者名')),
                ('client_kana', models.CharField(max_length=100, verbose_name='ふりがな')),
                ('client_gender', models.CharField(choices=[('男性', '男'), ('女性', '女')], max_length=2, verbose_name='性別')),
                ('class_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_app.class_num')),
                ('class_obst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_app.class_obst')),
            ],
        ),
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurer_name', models.CharField(default=1, max_length=6, verbose_name='保険者')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_app.client')),
                ('service_records', models.ManyToManyField(to='invoice_app.actual')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addons', models.ManyToManyField(to='invoice_app.addontype')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=6)),
                ('class_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_app.class_num')),
                ('class_obst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_app.class_obst')),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_app.insurer')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(choices=[('A', '日中一時支援（〜４）'), ('B', '日中一時支援（４〜８）'), ('C', '日中一時支援（８〜）'), ('D', '日中一時(併給）'), ('E', '生活介護')], max_length=1)),
                ('insurers', models.ManyToManyField(through='invoice_app.ServicePrice', to='invoice_app.insurer')),
            ],
        ),
        migrations.AddField(
            model_name='serviceprice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_app.servicetype'),
        ),
        migrations.CreateModel(
            name='ServiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceline_set', to='invoice_app.invoice')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice_app.service')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='insurer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_app.insurer'),
        ),
        migrations.AddField(
            model_name='actual',
            name='addons',
            field=models.ManyToManyField(to='invoice_app.addontype'),
        ),
        migrations.AddField(
            model_name='actual',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice_app.servicetype', verbose_name='サービスタイプ'),
        ),
        migrations.AddField(
            model_name='actual',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_app.client', verbose_name='利用者名'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceprice',
            unique_together={('insurer', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='actual',
            unique_together={('user_name', 'date')},
        ),
    ]
