# Generated by Django 4.2.1 on 2023-05-12 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=20)),
                ('client_kana', models.CharField(max_length=100)),
                ('client_gender', models.CharField(choices=[('男性', '男'), ('女性', '女')], max_length=2)),
                ('number', models.CharField(max_length=15)),
                ('insurer', models.CharField(max_length=10)),
                ('room_number', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Actual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('bathing', models.BooleanField(default=True)),
                ('transportation', models.BooleanField(default=True)),
                ('meal', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_app.client')),
            ],
        ),
    ]
