# Generated by Django 4.2.1 on 2023-10-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='insurance_id',
            field=models.IntegerField(null=True, verbose_name='受給者番号'),
        ),
        migrations.AddField(
            model_name='client',
            name='max_amount',
            field=models.IntegerField(null=True, verbose_name='負担上限額'),
        ),
    ]
