# Generated by Django 4.2.1 on 2023-08-15 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='insurer',
            field=models.ForeignKey(default='宇部市', on_delete=django.db.models.deletion.CASCADE, to='invoice_app.insurer'),
        ),
        migrations.AlterField(
            model_name='client',
            name='insurer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_app.insurer'),
        ),
        migrations.AlterField(
            model_name='insurer',
            name='insurer_name',
            field=models.CharField(default='宇部市', max_length=6, verbose_name='保険者'),
        ),
    ]
