# Generated by Django 4.2.1 on 2023-05-14 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actual',
            name='bathing',
            field=models.BooleanField(default=True, verbose_name='入浴'),
        ),
        migrations.AlterField(
            model_name='actual',
            name='date',
            field=models.DateField(verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='actual',
            name='end_time',
            field=models.TimeField(verbose_name='終了時刻'),
        ),
        migrations.AlterField(
            model_name='actual',
            name='meal',
            field=models.BooleanField(default=True, verbose_name='食事'),
        ),
        migrations.AlterField(
            model_name='actual',
            name='notes',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='actual',
            name='start_time',
            field=models.TimeField(verbose_name='開始時刻'),
        ),
        migrations.AlterField(
            model_name='actual',
            name='transportation',
            field=models.BooleanField(default=True, verbose_name='送迎'),
        ),
        migrations.AlterField(
            model_name='actual',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_app.client', verbose_name='利用者名'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_gender',
            field=models.CharField(choices=[('男性', '男'), ('女性', '女')], max_length=2, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_kana',
            field=models.CharField(max_length=100, verbose_name='ふりがな'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=20, verbose_name='利用者名'),
        ),
        migrations.AlterField(
            model_name='client',
            name='insurer',
            field=models.CharField(max_length=10, verbose_name='保険者'),
        ),
        migrations.AlterField(
            model_name='client',
            name='number',
            field=models.CharField(max_length=15, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='client',
            name='room_number',
            field=models.CharField(max_length=10, null=True, verbose_name='部屋番号'),
        ),
    ]
