# Generated by Django 4.2.1 on 2023-05-16 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0002_alter_actual_bathing_alter_actual_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actual',
            name='end_time',
            field=models.TimeField(default=datetime.time(15, 0), verbose_name='終了時刻'),
        ),
        migrations.AlterField(
            model_name='actual',
            name='start_time',
            field=models.TimeField(default=datetime.time(10, 0), verbose_name='開始時刻'),
        ),
        migrations.AlterUniqueTogether(
            name='actual',
            unique_together={('user_name', 'date')},
        ),
    ]
