# Generated by Django 4.2.1 on 2023-09-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0002_alter_serviceprice_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actual',
            name='ds',
            field=models.CharField(choices=[('日中一時', '日中一時'), (2, '生活介護'), (3, '併給')], max_length=30),
        ),
    ]
