# Generated by Django 4.2.1 on 2023-09-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0003_alter_actual_ds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actual',
            name='ds',
            field=models.CharField(choices=[('日中一時', '日中一時'), ('生活介護', '生活介護'), ('併給', '併給')], max_length=30),
        ),
    ]
