# Generated by Django 4.2.1 on 2023-10-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0003_alter_client_insurance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='insurance_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='受給者番号(日中一時)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='max_amount',
            field=models.IntegerField(default=0, verbose_name='負担上限額'),
        ),
    ]
