# Generated by Django 4.2.1 on 2023-10-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0004_alter_client_insurance_id_alter_client_max_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='insurance_id',
            field=models.CharField(blank=True, null=True, verbose_name='受給者番号(日中一時)'),
        ),
    ]
