# Generated by Django 4.2.1 on 2023-09-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0004_alter_actual_ds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actual',
            name='bathing',
        ),
        migrations.RemoveField(
            model_name='actual',
            name='transportation',
        ),
        migrations.AddField(
            model_name='actual',
            name='transportation1',
            field=models.BooleanField(default=True, verbose_name='送迎（迎え）'),
        ),
        migrations.AddField(
            model_name='actual',
            name='transportation2',
            field=models.BooleanField(default=True, verbose_name='送迎（送り）'),
        ),
        migrations.AlterField(
            model_name='actual',
            name='ds',
            field=models.CharField(choices=[('日中一時', '日中一時'), ('生活介護', '生活介護'), ('併給', '併給')], default='日中一時', max_length=30, verbose_name='サービス種'),
        ),
    ]
