# Generated by Django 4.2.1 on 2023-10-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0005_alter_client_insurance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_num',
            name='category',
            field=models.CharField(max_length=5, verbose_name='障害区分'),
        ),
        migrations.AlterField(
            model_name='class_obst',
            name='category',
            field=models.CharField(max_length=5, verbose_name='障害種別'),
        ),
    ]
