# Generated by Django 4.2.1 on 2023-09-30 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0006_actual_trans_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actual',
            name='trans_counts',
        ),
    ]
