# Generated by Django 4.2.1 on 2023-09-30 23:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0007_remove_actual_trans_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='actual',
            name='trans_counts',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)]),
        ),
    ]
